const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
const BEGIN_API_CALL = 'BEGIN_API_CALL';
const API_CALL_ERROR = 'API_CALL_ERROR';
const DELETE_COURSE_OPTIMISTIC = 'DELETE_COURSE_OPTIMISTIC';

const actionTypes = {
    LOAD_COURSES_SUCCESS,
    LOAD_AUTHORS_SUCCESS,
    CREATE_COURSE_SUCCESS,
    UPDATE_COURSE_SUCCESS,
    BEGIN_API_CALL,
    API_CALL_ERROR,
    DELETE_COURSE_OPTIMISTIC
}

export default actionTypes;